name = "medium-backend"
compatibility_date = "2023-12-01"



[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTI2MDRhNzUtN2U3Ny00OTNmLWI2ZmQtNGM1MGExZTk0OGI2IiwidGVuYW50X2lkIjoiNWQwN2JhODQ2NDUxNDU1MDk0YTI5ZDU3NThlY2Q4YzU4YjU4N2U2OTU1YTM0NmE0YzIyNzkwMDJjNTM1NDNkNCIsImludGVybmFsX3NlY3JldCI6IjFkMjBkMGUzLTZiOTMtNDVlMC1iMGM5LWY2ZGU4OWM1OGViZSJ9.CySB_tJMg7Da1RcdwVcrgku9nrekEnWoORU9TzcEE0Q"

JWT_SECRET="mysupersecret"